openapi: 3.0.0
info:
  title: Thornode Auth TradeAccounts API
  version: 3.19.1
  contact:
    email: devs@thorchain.org
  description: Thornode REST API.
tags:
- name: TradeAccounts
paths:
  /thorchain/trade/accounts/{asset}:
    parameters:
    - $ref: '#/components/parameters/queryHeight'
    - $ref: '#/components/parameters/asset'
    get:
      description: Returns all trade accounts for an asset
      operationId: trade_accounts
      tags:
      - TradeAccounts
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TradeAccountsResponse'
components:
  parameters:
    asset:
      name: asset
      in: path
      required: true
      schema:
        type: string
        example: BTC.BTC
    queryHeight:
      name: height
      in: query
      description: optional block height, defaults to current tip
      required: false
      schema:
        type: integer
        format: int64
        minimum: 0
  schemas:
    TradeAccountResponse:
      type: object
      required:
      - asset
      - units
      - owner
      properties:
        asset:
          type: string
          example: BTC~BTC
          description: trade account asset with "~" separator
        units:
          type: string
          description: units of trade asset belonging to this owner
        owner:
          type: string
          description: thor address of trade account owner
        last_add_height:
          type: integer
          format: int64
          description: last thorchain height trade assets were added to trade account
        last_withdraw_height:
          type: integer
          format: int64
          description: last thorchain height trade assets were withdrawn from trade account
    TradeAccountsResponse:
      type: array
      items:
        $ref: '#/components/schemas/TradeAccountResponse'
