openapi: 3.0.0
info:
  title: Thornode Auth SecuredAsset API
  version: 3.19.1
  contact:
    email: devs@thorchain.org
  description: Thornode REST API.
tags:
- name: SecuredAsset
paths:
  /thorchain/securedasset/{asset}:
    parameters:
    - $ref: '#/components/parameters/queryHeight'
    - $ref: '#/components/parameters/asset'
    get:
      description: Returns the total size and ratio of a secured asset
      operationId: secured_asset
      tags:
      - SecuredAsset
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SecuredAssetResponse'
components:
  parameters:
    asset:
      name: asset
      in: path
      required: true
      schema:
        type: string
        example: BTC.BTC
    queryHeight:
      name: height
      in: query
      description: optional block height, defaults to current tip
      required: false
      schema:
        type: integer
        format: int64
        minimum: 0
  schemas:
    SecuredAssetResponse:
      type: object
      required:
      - asset
      - supply
      - depth
      properties:
        asset:
          type: string
          example: BTC-BTC
          description: secured account asset with "-" separator
        supply:
          type: string
          description: total share tokens issued for the asset
        depth:
          type: string
          description: total deposits of the asset
