openapi: 3.0.0
info:
  title: Thornode Auth API
  version: 3.19.1
  contact:
    email: devs@thorchain.org
  description: Thornode REST API.
tags:
- name: Auth
paths:
  /auth/accounts/{address}:
    parameters:
    - $ref: '#/components/parameters/queryHeight'
    - $ref: '#/components/parameters/address'
    get:
      description: Returns account information for the provided address.
      operationId: account
      tags:
      - Auth
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountResponse'
components:
  schemas:
    AccountResponse:
      type: object
      properties:
        result:
          type: object
          properties:
            value:
              $ref: '#/components/schemas/Account'
    Account:
      type: object
      properties:
        type:
          type: string
          example: /cosmos.auth.v1beta1.BaseAccount
        address:
          type: string
          example: thor1f3s7q037eancht7sg0aj995dht25rwrnu4ats5
        pubkey:
          type: string
          example: thorpub1addwnpepq27ck6u44zl8qqdnmzjjc8rg72amrxrsp42p9vd7kt6marhy6ww76z8shwe
        sequence:
          type: integer
          format: int64
          example: 1234
        account_number:
          type: integer
          format: int64
          example: 1234
  parameters:
    address:
      name: address
      in: path
      required: true
      schema:
        type: string
        example: thor1zupk5lmc84r2dh738a9g3zscavannjy3nzplwt
    queryHeight:
      name: height
      in: query
      description: optional block height, defaults to current tip
      required: false
      schema:
        type: integer
        format: int64
        minimum: 0
