openapi: 3.0.0
info:
  title: Thornode Auth Thornames API
  version: 3.19.1
  contact:
    email: devs@thorchain.org
  description: Thornode REST API.
tags:
- name: Thornames
paths:
  /thorchain/thorname/{name}:
    parameters:
    - $ref: '#/components/parameters/queryHeight'
    - name: name
      in: path
      description: the thornode to lookup
      required: true
      schema:
        type: string
    get:
      description: Returns addresses registered to the provided thorname.
      operationId: thorname
      tags:
      - Thornames
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThornameResponse'
components:
  schemas:
    ThornameResponse:
      $ref: '#/components/schemas/Thorname'
    ThornameAlias:
      type: object
      properties:
        chain:
          type: string
          example: BTC
        address:
          type: string
          example: bc1qn9esxuw8ca7ts8l6w66kdh800s09msvutydc46
    Thorname:
      type: object
      required:
      - preferred_asset
      - aliases
      properties:
        name:
          type: string
          example: thor
        expire_block_height:
          type: integer
          format: int64
          example: 1234
        owner:
          type: string
          example: thor1f3s7q037eancht7sg0aj995dht25rwrnu4ats5
        preferred_asset:
          type: string
          example: BTC.BTC
        preferred_asset_swap_threshold_rune:
          type: string
          example: '500'
          description: Amount of RUNE currently needed to trigger a preferred asset swap.
        affiliate_collector_rune:
          type: string
          example: '100'
          description: Amount of RUNE currently accrued by this thorname in affiliate fees waiting to be swapped to preferred asset.
        aliases:
          type: array
          items:
            $ref: '#/components/schemas/ThornameAlias'
  parameters:
    queryHeight:
      name: height
      in: query
      description: optional block height, defaults to current tip
      required: false
      schema:
        type: integer
        format: int64
        minimum: 0
